"""Generate style sheets from ``yusina.tokens``.

    python -m yusina.generate

writes to ``yusina/data/``: one ``yusina-<register>.mplstyle`` and ``.plotly.json`` per
``tokens.REGISTERS`` entry, and ``palette_tags.csv``. Other libraries (plotly, altair, ...) get
their own ``write_*`` here later, all fed from the same tokens.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib as mpl
import polars as pl
from cycler import Cycler

from yusina import palettes
from yusina import tokens as t
from yusina._rcparams import build_rc

DATA = Path(__file__).parent / "data"


def _scalar(v) -> str:
    if isinstance(v, float):
        return repr(round(v, 6))
    return str(v)


def _fmt(v) -> str:
    # matplotlib treats '#' as a comment in .mplstyle, so hex colours must be
    # quoted, and cycle colours are written bare (6-hex, no '#').
    if isinstance(v, Cycler):
        cols = [c.lstrip("#") for c in v.by_key()["color"]]
        return "cycler('color', [{}])".format(", ".join(repr(c) for c in cols))
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, str):
        return f'"{v}"' if "#" in v else v
    if isinstance(v, (list, tuple)):
        return ", ".join(_scalar(x) for x in v)
    return _scalar(v)


def write_mplstyle(register: str = t.DEFAULT_REGISTER, path: Path | str | None = None) -> Path:
    """Serialise ``build_rc(1.0, register)`` to a matplotlib .mplstyle file.

    Only keys the installed matplotlib recognises are written, so the file
    stays loadable across versions.
    """
    path = Path(path or DATA / f"yusina-{register}.mplstyle")
    rc = build_rc(1.0, register)
    valid = set(mpl.rcParams)
    header = [
        f"# yusina matplotlib style ({register}) -- AUTO-GENERATED by `python -m yusina.generate`",
        "# from yusina/tokens.py. Edit tokens.py and regenerate; do not edit here.",
        "",
    ]
    body, prev = [], None
    for key in sorted(rc):
        if key not in valid:
            continue
        group = key.split(".")[0]
        if prev is not None and group != prev:
            body.append("")
        prev = group
        body.append(f"{key}: {_fmt(rc[key])}")
    path.write_text("\n".join(header + body) + "\n")
    return path


def write_palette_tags(path: Path | str = DATA / "palette_tags.csv") -> Path:
    """One row per palette, one column per computed tag (base fields stay in
    ``palettes.csv``); list / dict tags are space-separated strings."""
    rows = []
    for name in palettes.PALETTES:
        t = {k: v for k, v in palettes.tags(name).items() if k not in palettes.Palette.__annotations__}
        t["hue_names"] = " ".join(t["hue_names"])
        t["schemes_by_n"] = " ".join(f"{n}:{s}" for n, s in t["schemes_by_n"].items())
        rows.append({"name": name, **t})
    path = Path(path)
    pl.DataFrame(rows).write_csv(path)
    return path


def write_plotly_template(register: str = t.DEFAULT_REGISTER, path: Path | str | None = None) -> Path:
    """Serialise ``backends.plotly_template(1.0, register)`` to ``yusina-<register>.plotly.json``."""
    from yusina.backends import plotly_template

    path = Path(path or DATA / f"yusina-{register}.plotly.json")
    path.write_text(json.dumps(plotly_template(1.0, register).to_plotly_json(), indent=1))
    return path


def main() -> None:
    for register in t.REGISTERS:
        print("wrote", write_mplstyle(register))
        print("wrote", write_plotly_template(register))
    print("wrote", write_palette_tags())


if __name__ == "__main__":
    main()
