"""Generate style sheets from ``yusina.tokens``.

    python -m yusina.generate

writes ``yusina/yusina.mplstyle``. Other libraries (plotly, altair, ...) get
their own ``write_*`` here later, all fed from the same tokens.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
from cycler import Cycler

from yusina._rcparams import build_rc

HERE = Path(__file__).parent


def _scalar(v) -> str:
    if isinstance(v, float):
        return repr(round(v, 6))
    return str(v)


def _fmt(v) -> str:
    # matplotlib treats '#' as a comment in .mplstyle, so hex colours must be
    # quoted, and cycle colours are written bare (6-hex, no '#').
    if isinstance(v, Cycler):
        cols = [c.lstrip("#") for c in v.by_key()["color"]]
        return "cycler('color', [%s])" % ", ".join(repr(c) for c in cols)
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, str):
        return '"%s"' % v if "#" in v else v
    if isinstance(v, (list, tuple)):
        return ", ".join(_scalar(x) for x in v)
    return _scalar(v)


def write_mplstyle(path: Path | str = HERE / "yusina.mplstyle") -> Path:
    """Serialise ``build_rc(1.0)`` to a matplotlib .mplstyle file.

    Only keys the installed matplotlib recognises are written, so the file
    stays loadable across versions.
    """
    path = Path(path)
    rc = build_rc(1.0)
    valid = set(mpl.rcParams)
    header = [
        "# yusina matplotlib style -- AUTO-GENERATED by `python -m yusina.generate`",
        "# from yusina/tokens.py. Edit tokens.py and regenerate; do not edit here.",
        "",
    ]
    body, prev = [], None
    for key in sorted(rc):
        if key not in valid:
            continue
        group = key.split(".")[0]
        if prev is not None and group != prev:
            body.append("")
        prev = group
        body.append(f"{key}: {_fmt(rc[key])}")
    path.write_text("\n".join(header + body) + "\n")
    return path


def main() -> None:
    print("wrote", write_mplstyle())


if __name__ == "__main__":
    main()
